# Week 2: Model Selection & Curse of Dimensionality

Your task for today is to create the __most generalizable__ model from datasets of different sizes. 

We will use 3 partitions of the [Titanic](https://www.kaggle.com/c/titanic) dataset of size 100, 400, and 891. This is a fairly straightforward binary classification task with the goal of predicting _who survived_0 when the Titanic sunk. 

The dataset has the following columns: 

| Variable | Definition                                 | Key                                            |   |   |
|:----------|:--------------------------------------------|:------------------------------------------------|---|---|
| Survival | Survival                                   | 0 = No, 1 = Yes                                |   |   |
| Pclass   | Ticket class                               | 1 = 1st, 2 = 2nd, 3 = 3rd                      |   |   |
| Sex      | Sex                                        |                                                |   |   |
| Age      | Age in years                               |                                                |   |   |
| Sibsp    | # of siblings / spouses aboard the Titanic |                                                |   |   |
| Parch    | # of parents / children aboard the Titanic |                                                |   |   |
| Ticket   | Ticket number                              |                                                |   |   |
| Fare     | Passenger fare                             |                                                |   |   |
| Cabin    | Cabin number                               |                                                |   |   |
| Embarked | Port of Embarkation                        | C = Cherbourg, Q = Queenstown, S = Southampton |   |   |




There are some pecularities in the data: some columns contain missing values, some are redundant, and some might only be useful with feature engineering.

__Exercise__:

The following shows a simple example of fitting a logistic regression model to the data with 400 training examples.

- Run the code and discuss ways to improve it

In [635]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
from collections import Counter

In [612]:
data_folder = "titanic" # set to the name of the folder where you keep the data
test = pd.read_csv(os.path.join(data_folder, "test.csv"))
train = pd.read_csv(os.path.join(data_folder, "train_100.csv"))
#train = pd.read_csv(os.path.join(data_folder, "train_400.csv"))
#train = pd.read_csv(os.path.join(data_folder, "train_full.csv"))


In [613]:
# Let's take a quick look at the data
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [614]:
# And the test set
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Survived         0
dtype: int64

In [615]:
# Okay, lots of missing age values. Filling them with the mean value of the column
train["Age"] = train["Age"].fillna(train["Age"].mean())
test["Age"] = test["Age"].fillna(train["Age"].mean())

# 1 missing Fare in test, filling with the mean
test["Fare"] = test["Fare"].fillna(train["Fare"].mean())

# Mean imputation is very naive - can you think of better ways to impute the missing values?

In [616]:
# Let's see if it worked
train.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age             0
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          80
Embarked        1
dtype: int64

In [617]:
# sklearn does not like columns with  categorical values
# make them binary dummy variables instead
train = pd.get_dummies(train, columns=["Pclass", "Embarked", "Sex"])
test =  pd.get_dummies(test, columns=["Pclass", "Embarked", "Sex"])

In [618]:
train.head()

PassengerId  Survived                                               Name  \
0            1         0                            Braund, Mr. Owen Harris   
1            2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3         1                             Heikkinen, Miss. Laina   
3            4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5         0                           Allen, Mr. William Henry   

    Age  SibSp  Parch            Ticket     Fare Cabin  Pclass_1  Pclass_2  \
0  22.0      1      0         A/5 21171   7.2500   NaN         0         0   
1  38.0      1      0          PC 17599  71.2833   C85         1         0   
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN         0         0   
3  35.0      1      0            113803  53.1000  C123         1         0   
4  35.0      0      0            373450   8.0500   NaN         0         0   

   Pclass_3  Embarked_C  Embarked_Q  Embarked_S  Sex_female  Sex_male  
0         1           0           0           1           0         1  
1         0           1           0           0           1         0  
2         1           0           0           1           1         0  
3         0           0           0           1           1         0  
4         1           0           0           1           0         1

In [619]:
def binarize_cabin(df):
   cabins = df["Cabin"].values
   df["Cabin_binary"] = [1 if isinstance(cabin, str) else 0 for cabin in cabins]
   return df

train, test = binarize_cabin(train), binarize_cabin(test)

In [620]:
# The Ticket, PassengerId, Name, and Cabin column seem like they might be problematic
# Let's check how many unique values they contain
print(f"N. of rows: {len(train)}")

for col in ["Ticket", "PassengerId", "Name", "Cabin"]:
    print(f"Proportion of unique values in {col}: {len(train[col].unique()) / len(train)}")

N. of rows: 100
Proportion of unique values in Ticket: 0.97
Proportion of unique values in PassengerId: 1.0
Proportion of unique values in Name: 1.0
Proportion of unique values in Cabin: 0.2


In [621]:
# PassengerId, Name, and Ticket are practically unique for each individual and thus unusable for predictions
# Cabin has a lot of missing values and a lot of unique values. Dropping the columns

uninformative_cols = ["PassengerId", "Name", "Ticket", "Cabin", "Parch", "SibSp", "Embarked_C", "Embarked_Q", "Embarked_S"] #
train = train.drop(columns=uninformative_cols)
test = test.drop(columns=uninformative_cols)

# Could Cabin be made informative with some feature engineering?

In [622]:
# Creating a good old logistic regression model based on the remaining columns
#model = LogisticRegression()
model = RandomForestClassifier(max_depth=50, n_estimators = 60, n_jobs = -1, class_weight = "balanced", random_state=42)
# Make subset of training data containing everything except the label
X = train.loc[:, train.columns != "Survived"]
# Make subset containing only the label
Y = train["Survived"]

In [623]:
 # Fit model on training data
 model.fit(X, Y)
 # See how well the model does on the training data
 yhat = model.predict(X)

In [624]:
print(f"Accuracy on train data: {accuracy_score(Y, yhat)}")
confusion_matrix(Y, yhat)

Accuracy on train data: 1.0


array([[59,  0],
       [ 0, 41]], dtype=int64)

In [625]:
# Test the model on the testing set
X_test = test.loc[:, train.columns != "Survived"]
Y_test = test["Survived"]

In [626]:
yhat_test = model.predict(X_test)
print(f"Accuracy on test data: {accuracy_score(Y_test, yhat_test)}")
confusion_matrix(Y_test, yhat_test)

Accuracy on test data: 0.8779904306220095


array([[266,   0],
       [ 51, 101]], dtype=int64)

.. That was not very impressive. Our expectation of performance was horribly miscalibrated, as we fared much worse on the test set than on our training set. Our model also seems to overpredict survival on the test data.

Now it's your turn to do better

__Exercises__:

Discuss:

- How can you get a better estimate of the out-of-sample performance?
- How can you reduce overfitting to the training data?
- Do you need different strategies for model creation for the different sizes of dataset?
    - If so, what would you do differently?

Code:

- For each partition (i.e. each dataset) create at least 3 different models that you expect to generalize well. Evaluate them on the training sample using some form of model selection (cross-validated performance, held-out data, information criteria etc.) and choose one to test on the testing set. Your goal is to create the best performing, most well-calibrated model, ie. training performance should be close to testing performance (and performance should of course be high!). 
- Test how good performance you can get on the small datasets with clever optimization and regularization.

For next time:

- In your study groups, prepare a 3-5 min presentation on something interesting about your solution: Did you create some cool functions for preprocessing, test an exciting new type of model, set everything up to be run from the command line, or perhaps you're just really excited about the performance of your model. No need for slideshows, but feel free to show code.

---

Tips to get started:
- Visualization can often be a good way to get started: how is the distribution of the variables? are any of them highly correlated?
- Instead of training and testing on the whole training data, implement a form of cross-validation ([sk-learn makes it easy](https://scikit-learn.org/stable/modules/cross_validation.html#computing-cross-validated-metrics))
- Remember ridge regularization from last week? [Try it](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeClassifier.html)
- Check out a list of models in sk-learn [here](https://scikit-learn.org/stable/supervised_learning.html)
- Lost or out of ideas? Take some inspiration from entries in the [original Kaggle challenge](https://www.kaggle.com/c/titanic/code)

Things to try:
- You might be able to get more information out of the predictors if you do some feature engineering. Perhaps add a column indicating whether the person had a cabin or not, or one calculating the family size?
- Calculating information criteriais not entirely straight-forward in sk-learn. [This tutorial](https://machinelearningmastery.com/probabilistic-model-selection-measures/) might help
- The outcome (survival) is not completely balanced. Over-/under-sampling might help
- Ensemble models often generalize better than single models. Try one of the methods [here](https://scikit-learn.org/stable/modules/ensemble.html)
- Don't feel restricted to sk-learn. Feel to make a Bayesian model in [PyMC3](https://github.com/pymc-devs/pymc3) or any other framework you want
- High-performance interpretable models are all the rage right now. [Try one of them!](https://github.com/interpretml/interpret) 


In [636]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import RidgeClassifier

def get_cross(model, X, Y, cv = 8, scoring = "f1_weighted"):
    scores = cross_val_score(model, X, Y, cv=8, scoring = "f1_weighted")
    print(f"mean = {np.mean(scores)}, sd = {np.std(scores)}")
    return (np.mean(scores), np.std(scores))

get_cross(LogisticRegression(), X, Y)
get_cross()

mean = 0.8159642559918294, sd = 0.07789190574978622


(0.8159642559918294, 0.07789190574978622)

In [628]:
scores = cross_val_score(RandomForestClassifier(n_estimators = 60, n_jobs = -1, random_state = 42), X, Y, cv =8, scoring = "f1_weighted")
print(f"mean = {np.mean(scores)}, sd = {np.std(scores)}")

mean = 0.7859282516911194, sd = 0.09591366355396944


In [629]:
scores = cross_val_score(MLPClassifier(solver = "adam", alpha = 0.001, hidden_layer_sizes=(1000,100), random_state = 1, learning_rate = "adaptive"), X, Y, cv = 8, scoring = "f1_weighted")
print(f"mean = {np.mean(scores)}, sd = {np.std(scores)}")

mean = 0.7433981255672433, sd = 0.10258187811659435


In [630]:
scores = cross_val_score(AdaBoostClassifier(), X, Y, cv = 8, scoring = "f1_weighted")
print(f"mean = {np.mean(scores)}, sd = {np.std(scores)}")

mean = 0.7242467499820442, sd = 0.11516803449205537


In [631]:
scores = cross_val_score(RidgeClassifier(), X, Y, cv = 8, scoring = "f1_weighted")
print(f"mean = {np.mean(scores)}, sd = {np.std(scores)}")

mean = 0.8179610150198385, sd = 0.1013740956007625


In [632]:
from interpret.glassbox import LogisticRegression, ExplainableBoostingClassifier
#from interpret.greybox import DecisionTreeClassifier
from interpret import show

ebm_log = LogisticRegression()
ebm_log.fit(X, Y)

emb_exp = ExplainableBoostingClassifier()
emb_exp.fit(X,Y)

ebm_global = emb_exp.explain_global()
show(ebm_global)

# or substitute with LogisticRegression, DecisionTreeClassifier, RuleListClassifier, ...
# EBM supports pandas dataframes, numpy arrays, and handles "string" data natively.

<!-- http://127.0.0.1:7001/2716229856128/ -->

In [633]:
y_hat_test = emb_exp.predict(X_test)
print(f"Accuracy on test data: {accuracy_score(Y_test, yhat_test)}")
confusion_matrix(Y_test, yhat_test)

Accuracy on test data: 0.8779904306220095


array([[266,   0],
       [ 51, 101]], dtype=int64)